### PR TITLE
graceful endings

### PR DESCRIPTION
**Pull request by tetsuo**
allowing half open mode fixes failing test and prevents [this](https://github.com/maxogden/multiplex/blob/ece379baf1fd46f88b5d50992633df4cbf6532a4/index.js#L67) kicking in

### CODE REVIEW

**Comment by tetsuo** [comment]
@substack are you watching this repo?

**Comment by substack** [comment]
Which test was failing?

**Comment by tetsuo** [comment]
both stream and stream_and_rpc

**Comment by bcomnes** [comment]
They are passing for me.   

```
TAP version 13
# duplex
ok 1 should be equal
# stream
ok 2 should be equal
# stream and rpc
(node:7225) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
ok 3 should be equal

1..3
# tests 3
# pass  3

# ok
```

But `has()` is no longer being used in index.

**Pull request closed without merging**
